version: "3.4"
services:
  app:
    build:
      context: .
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=0.0.0:5005 -jar out/pass.jar
    tty: true
    stdin_open: true
    ports:
      - 5005:5005